# Generated by Django 3.2.4 on 2021-06-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Barco',
            fields=[
                ('idTipoBarco', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tipo de barco')),
                ('nombreTipoBarco', models.CharField(max_length=50, verbose_name='Nombre del tipo de barco')),
            ],
        ),
        migrations.CreateModel(
            name='Barco',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre del barco')),
                ('año', models.CharField(max_length=4, verbose_name='agno')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descripcion del barco')),
                ('tipo_barco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appQuat.tipo_barco')),
            ],
        ),
    ]
